<?php

if (count($array) > 0) {
    //
}

if ((anotherFunc($array) !== 0) && count($array) > 0) {
    //
}

if ((count($array) !== 0) && (((anotherFunc($array))))) {
    //
}

if (((count($array)))) {
    //
}

if (count($array) && (anotherFunc($array) !== 0)) {
    //
}

if ($findme === 'a' && (count($array) || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (count($array) != 0 || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (count($array) > 10 || $findme !== 'b') && $mystring !== false) {
    //
}

if (($column->getId() === 'store_id' || count($array) > 0 || $column->getId() === 'status') && $column->getFilter()->getValue()) {
    //
}

$length = count($array);

if ('count' != $foo && count($bar)) {
    //
}

if ($findme === 'a' and (count($array) != 0 or $findme !== 'b') and $mystring !== false) {
    //
}
