<?php

if (strlen($string) > 0) {
    //
}

if ((anotherFunc($string) !== 0) && strlen($string) > 0) {
    //
}

if ((strlen($string) !== 0) && (((anotherFunc($string))))) {
    //
}

if (((strlen($string)))) {
    //
}

if (strlen($string) && (anotherFunc($string) !== 0)) {
    //
}

if ($findme === 'a' && (strlen($string) || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (strlen($string) != 0 || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (strlen($string) > 10 || $findme !== 'b') && $mystring !== false) {
    //
}

if (($column->getId() === 'store_id' || strlen($string) > 0 || $column->getId() === 'status') && $column->getFilter()->getValue()) {
    //
}

if (strlen($string . implode(',', $array)) && (anotherFunc($string) !== 0)) {
    //
}

if (strlen($string . implode(',', $array)) > 10 && (anotherFunc($string) !== 0)) {
    //
}

$length = strlen($string);

if ($findme === 'a' and (strlen($string) > 0 or $findme !== 'b') and $mystring !== false) {
    //
}
